[http]
http_addr = ":8080"
scheme = "http"

[logs]
access_log = false
path = ""
level = "trace"

[credential]
accesskey = "1GL02rRYQxK8s7FQh8dV"
secketkey = "2IDjaPOpFfkq5Zf9K4tKu8k5AKApY8S8eKV1zsRl"

[storage]
type = "posix"

[storage.swift]
addr = "http://192.168.20.6/v1"
authurl="http://192.168.20.6:5000/v3/auth/tokens"
tenantname="test"
username="wps"
projname="wps"
password="12345"

[storage.s3]
#addr = "http://kss.ksyun.com"
#accesskey = "lMQTr0hNlMpB0iOk/i+x"
#secretkey = "D4CsYLs75JcWEjbiI22zR3P7kJ/+5B1qdEje7A7I"

#addr = "http://192.168.11.139:80"
#accesskey = "BMNW5JUYO889ZDZYA8GH"
#secretkey = "Pb4BZGgQD1hV7UE1V0qf85f3YNSltizHVntdLyyn"

addr = "http://192.168.20.3:8888"
accesskey = "ZAZW0PO781UDXLA4HGC7"
secretkey = "ORBLBg0P6kdObZ6uudMDEWuiTUPNKMwArNyHWRNu"

[storage.oss]
addr = "oss-cn-beijing.aliyuncs.com"
accesskey = "LTAIhi5D4D1nAg1g"
secretkey = "scHgvkfUKwl10I4xRLduWNkQSwyjmr"

[storage.qiniu]
addr = "xxxx.com2.z0.glb.qiniucdn.com"
accesskey = "XXyour accesskeyXX"
secretkey = "XXyour secretkeyXX"

[storage.posix]
addr = "./bin"
